
language: go
go:
  - 1.7.6
  - 1.8.5
  - 1.9.2

build:
  ci:
    - go run hello.go
  on_success:
    - echo "works"




resources:
- name: myGoTestRepo
  type: gitRepo
  versionTemplate:
    sourceName: trriplejay/sample_go
    branch: master

jobs:
- name: sample_go_runCI
  type: runCI
  steps:
    - OUT: myGoTestRepo
      replicate: sample_go_ciRepo
